name: recipe_flutter_provider
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+8

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.15.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  http: ^1.2.1
  launch_review: ^3.0.1
  share: ^2.0.4
  material_design_icons_flutter: ^7.0.7296
  firebase_auth: ^4.1.0
  google_sign_in: ^6.1.2
  connectivity: ^3.0.6
  rate_my_app: ^2.1.0
  # firebase_admob: ^0.11.2

  google_mobile_ads: ^5.1.0

  flutter_login_facebook: ^2.0.0

# dependency_overrides:
  # flutter_facebook_login: ^3.0.0

  # flutter_facebook_login: any
  firebase_core: ^2.31.1
  firebase_remote_config: ^4.4.6
  firebase_analytics: ^10.10.6
  firebase_messaging: ^14.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loader.gif
    - assets/images/loader1.gif
    - assets/images/transparentBG.png
    - assets/images/checkmark.png
    - assets/images/close.png
    - assets/images/fbLogo.png
    - assets/images/google_logo.png
    - assets/images/app_icon.png
    - assets/images/noProfilePic.png
    - assets/images/skip.png
    - assets/images/loginBg.png
    - assets/images/no_recipe.png
    - assets/images/splash_bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
